"""Inject the generated benchmark table into README.md between markers.

Run after `notebooks/02_benchmarks.py`. The weekly benchmarks workflow calls
this on the scheduled `--long` run and commits the result, so the README
"Latest CI run" tables are reproducible CI measurements rather than
hand-entered numbers. Idempotent: re-running with the same table is a no-op
(modulo the timestamp line in the table).

Usage:
    python notebooks/02_benchmarks.py --long      # writes _artifacts/benchmark_table.md
    python notebooks/_update_readme.py            # injects it into README.md
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
TABLE = ROOT / "notebooks" / "_artifacts" / "benchmark_table.md"

START = (
    "<!-- BENCHMARKS:START - auto-generated by .github/workflows/benchmarks.yml; "
    "do not edit by hand -->"
)
END = "<!-- BENCHMARKS:END -->"


def _table_body() -> str:
    """Generated-table content, minus the H1 title and trailing attribution,
    with `##` section headers demoted to `####` so they nest under the
    README's `### Latest CI run` subsection."""
    out = []
    for line in TABLE.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):  # drop the table's own H1 title
            continue
        if line.startswith("Generated by"):  # drop trailing attribution
            continue
        if line.startswith("## "):  # ## Speed -> #### Speed (nest under ###)
            line = "##" + line
        out.append(line)
    return "\n".join(out).strip()


def main() -> int:
    if not TABLE.exists():
        print(f"error: {TABLE} not found - run notebooks/02_benchmarks.py first", file=sys.stderr)
        return 1
    readme = README.read_text(encoding="utf-8")
    if START not in readme or END not in readme:
        print("error: README.md is missing the BENCHMARKS markers", file=sys.stderr)
        return 1

    new_block = f"{START}\n\n{_table_body()}\n\n{END}"
    # Lambda replacement so backslash escapes in the table (e.g. `\~`) survive.
    updated = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        lambda _m: new_block,
        readme,
        count=1,
        flags=re.DOTALL,
    )
    if updated != readme:
        README.write_text(updated, encoding="utf-8")
        print("README.md benchmark table updated.")
    else:
        print("README.md already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
